stages: 
  - build
  - test

default:
# image: thchar/grenade_ci:latest
  before_script:
    - apt-get update >/dev/null
    - apt-get install -y locales >/dev/null
    - echo "en_US UTF-8" > /etc/locale.gen
    - locale-gen en_GB.UTF-8
    - export LANG=en_GB.UTF-8
    - export LANGUAGE=en_GB:en
    - export LC_ALL=en_GB.UTF-8

    - cabal update

# lint:
#   stage: lint
#   script: hlint .

build:
  stage: build
  script: cabal build

test: 
  stage: test
  script: cabal test --enable-tests --test-show-details=streaming --test-option=--color
