stages:
  - build
  - test
  - lint
  - bench

default:
# image: thchar/grenade_ci:latest
  before_script:
    - cabal update

lint:
  stage: lint
  script: hlint lint src/ test/ bench/ examples/

build:
  stage: build
  script: cabal build

test: 
  stage: test
  script: cabal test --enable-tests --test-show-details=streaming --test-option=--color

bench:
  stage: bench 
  script: cabal bench
  allow_failure: true
  when: manual